### ISSUE TITLE
Research ways to deliver dad jokes.

### ISSUE THREAD

**Issue by joe-riley** [amiedawn/jokinator#3]
The overall point of the application is to find good dad jokes and to send them to people somehow. We need a delivery system.

The work on this issue should include basic prototypes for a delivery method that uses an api key in a url query if possible and reporting back to the rest of the team to show the api and how it is used (if it is different or has any gotchas).

**Comment by ghost** [comment]
Update:

After spending the better part of a 8 hour day on research to this problem, I have found some barriers to entry.  I am currently building an application in node using the nexmo api to send a text message, example code below for general reference.  The major issue is neither OAuth or the use of node, however, the pricing.  Almost all of the text, email, or push notification apis will require OAuth, node or server-side languages such as; python, java, php, etc.  Ultimately the problem is price, the going rate is about $0.0050 per text on average.  Currently I am using my $2.00 signup credit to test.

Reference - https://developer.nexmo.com/documentation

```
const Nexmo = require('nexmo');

const nexmo = new Nexmo({
  apiKey: 'e7187240',
  apiSecret: 'B47R5Azs4EEWvMSA',
});

const from = '18209998745';
const to = '16235528817';
const text = 'Hello from Vonage SMS API';

nexmo.message.sendSms(from, to, text);
```

--------------------------------------------------

SendGrid API for email 100 emails/day for free.  SendGrid uses API Keys and again will require server-side languages as mentioned above, however, from a pricing standpoint may be our best bet if we want to move forward with sending a joke to a user.  See docs for more details, https://sendgrid.com/docs/API_Reference/api_v3.html.

--------------------------------------------------

Lastly, Facebook and Twitter API's

Facebook has a SendAPI "The Send API is the main API used to send messages to users, including text, attachments, structured message templates, sender actions, and more."

https://developers.facebook.com/docs/messenger-platform/reference/send-api/

Twitter API has Direct Message API with a variety of functionality.

https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/api-features

I only scratched the surface of the Facebook and Twitter API's.  It would be a good idea for all of us to take a look and see what functionality we could use to satisfy this issue.

**Comment by amiedawn** [comment]
Eek, yeah, we don't want something where we have to pay. :(

**Comment by amiedawn** [comment]
Rather than having all of us research the same thing, I have been looking on and off today at some alternatives to sharing in case that doesn't work out. I admittedly have been interrupted far too much to get very far, but most joke websites are severely lacking in "oomph." Most just have a listing of jokes in some form, like a simple list, cards, or a little more interesting like the one we saw last night where it was appearing to come from the bottom of a maze. So, if the texting or sharing doesn't work, maybe we look into other options of why would you want to visit a joke site if not to share them? I know a game can make it more complicated, but maybe some simplified contest or battle of the jokes. I will hopefully have less interruptions tonight and can come up with some better ideas that are feasible. Thanks for all your time and research today James!

**Comment by ghost** [comment]
I did add a suggestion in #5.  A Text-to-speech API, appears rather simple and will allow us to get an MVP out.  We can always revisit this issue at a later point, prior to submission.

**Comment by amiedawn** [comment]
Oh yes, I like that idea, and if it is pretty straightforward, that sounds
great! Sorry, I had seen that note and forgot!
