### ISSUE TITLE
Possible functionality of the site

### ISSUE THREAD

**Issue by amiedawn** [amiedawn/jokinator#5]

**Comment by joe-riley** [comment]
Amie! This is a great start to a ticket. I wish the Project Manager I worked with in my current roll stated this stuff and asked questions like this. 

- I like the functionality of joke rating and when we get to filling out more of the functionality that should be its own ticket as will a message board, I think. We can think of those existing in their own .js files that are used by the main js script, if we want to keep everything organized.
- The Nacho Libre design is cute and could probably be attached to the wireframe/design of the app so #1.
- I think the randomization should be a requirement of #2 since that code logic will probably live there.

I can make the changes I was talking about if that is ok with everyone and who knows maybe my separation of things just works in my head. What do you all think @amiedawn @JamesCostello-dev @sheilashix ?

**Comment by ghost** [comment]
Awesome ideas Amie!

Sounds good, Joe.  I think we should implement those changes.

**Comment by amiedawn** [comment]
Sounds good. Separation is good! :)  I am watching videos on Bulma. I like how they keep saying it is easy to use. :)

**Comment by ghost** [comment]
Some additional functionality.

- The ability for the user share via facebook using Dialog Share https://developers.facebook.com/docs/sharing/reference/share-dialog.

- The ability for the user to tweet via add Tweet button https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview

- Text-to-speech API https://rapidapi.com/voicerss/api/text-to-speech-1/details.  This API could satisfy our second API need for the project.

**Comment by ghost** [comment]
Any additional ideas beyond the current scope?  Or can we close this one out?

**Comment by amiedawn** [comment]
I think we are good to close this.
